# v https://github.com/codecov/example-go
language: go

go:
  - 1.8.x
  - 1.9.x
  - 1.10.x
  - tip

before_install:
  - go get -t -v ./... && go build -v ./...

script:
  - go vet ./...
  - go test -race -coverprofile=coverage.txt -covermode=atomic

after_success:
  - bash <(curl -s https://codecov.io/bash)
